name: Deploy Next.js Static Site to Hostinger

on:
  push:
    branches:
      - main # The branch you push changes to

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Build Next.js static site
        run: npm run build
        # This creates the 'out' folder

      - name: Deploy with FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: ${{ secrets.FTP_SERVER_DIR }}
          # The local directory to upload:
          local-dir: ./out/ 
          # Ensure the public_html is clean before uploading new static files
          delete-remote: true
